spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/internship23"
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 10000
      validation-timeout: 10000
      idle-timeout: 10000
      leak-detection-threshold: 10000
      max-lifetime: 3600000
      max-pool-size: 3
      min-idle: 1000
      is-auto-commit: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jackson:
    default-property-inclusion: non_absent
    serialization:
      write-dates-as-timestamps: false
  security:
    oauth2:
      resource-server:
        jwt:
          public-key-location: 'file:config/jwk-public.pem'

ro.axon.core:
  roles:
  - USER
  - HR
  - TEAM_LEAD
  token:
    domain: 'https://localhost:8081/'
    keyId: 'AXON'
    accessTokenDuration: 10 #minutes
    refreshTokenDuration: 20 #minutes
    publicKeyLocation: 'file:config/jwk-public.pem'
    privateKeyLocation: 'file:config/jwk-private.pem'

server.port: 8081
server:
  servlet:
    contextPath: /core


